name: CI

'on': [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2

      - name: Install npm packages
        run: npm install .

      - name: Check with Prettier
        run: npm run format:check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2

      - name: Install npm packages
        run: npm install .

      - name: Build
        run: npm run build
