name: CI

'on': [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Install npm packages
        run: npm install .

      - name: Check with Prettier
        run: npm run format:check

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3

      - name: Install npm packages
        run: npm install .

      - name: Build
        run: npm run build

      - name: Upload dist/ artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/

  docs:
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - uses: actions/checkout@v3

      - name: Download dist/
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist/

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          pip install -r docs/requirements.txt
          pip install ltd-conveyor

      - name: Build documentation
        working-directory: docs
        run: make html

      - name: Upload to LSST the Docs
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
        working-directory: docs
        run: ltd upload --product style-dictionary --gh --dir _build/html
